env: gridworld-v0
map: gridworldPlans&Goals/plan3.txt
rewards:
  0: -0.001
  3: 1
  4: 1
  5: -1
  6: -1
seed: 5
featExtractor: !!python/name:__main__.MapFromDumpExtractor4 ''
episodeLength: 100
freqSave: 1000
freqTest: 1000
nbTest: 100
freqVerbose: 10
fromFile: null
nbEpisodes: 1000000
mem_size: 1000000
lr: 0.001
epsilon: 0.2
eta: 0
gamma: 0.99
batch_size: 1000
C: 1000
learning_minimum: 100
hidden_dim:
  - 200
  - 200
target: true
replay: true
prior: false
learning_offset: 1000
device: "cuda:0"

# IGS parameters
beta: 0.9
alpha: 3
goal_buffer_size: 10
goalFreq: 10